# Generated by Django 4.0.2 on 2022-02-24 10:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_usergroup_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=10, validators=[django.core.validators.RegexValidator(message='Must be one of the following: rejected, pending or confirmed', regex='(rejected|pending|confirmed)$')])),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_receiver', to='accounts.usergroup')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_requestor', to='accounts.usergroup')),
            ],
            options={
                'db_table': 'matches',
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=10, validators=[django.core.validators.RegexValidator(message='Must be one of the following: rejected, pending or confirmed', regex='(rejected|pending|confirmed)$')])),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='accounts.usergroup')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='accounts.groupupuser')),
            ],
            options={
                'db_table': 'invite',
            },
        ),
    ]
