# Generated by Django 4.0.2 on 2022-03-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupup_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='have_met',
            field=models.BooleanField(default=False),
        ),
    ]
