# Generated by Django 4.0.2 on 2022-02-10 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import groupup.accounts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'interest',
            },
        ),
        migrations.CreateModel(
            name='GroupUpUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to=groupup.accounts.models.user_image_path)),
                ('interests', models.ManyToManyField(to='accounts.Interest')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groupupuser',
            },
        ),
    ]
