# Generated by Django 4.0.2 on 2022-02-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_groupupuser_birthday_usergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupupuser',
            name='interests',
            field=models.ManyToManyField(blank=True, to='accounts.Interest'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='interests',
            field=models.ManyToManyField(blank=True, to='accounts.Interest'),
        ),
    ]
