# Generated by Django 4.0.2 on 2022-02-15 12:13

from django.db import migrations, models
import groupup.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_groupupuser_interests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupupuser',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=groupup.accounts.models.user_image_path),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='group_pic',
            field=models.ImageField(blank=True, upload_to=groupup.accounts.models.group_image_path),
        ),
    ]
