# Generated by Django 4.0.2 on 2022-02-26 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_usergroup_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='num_of_members',
        ),
    ]
