# Generated by Django 4.0.2 on 2022-03-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_usergroup_num_of_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=30)),
                ('review', models.CharField(max_length=280)),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.AddField(
            model_name='usergroup',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='accounts.Reviews'),
        ),
    ]
