# Generated by Django 4.0.2 on 2022-03-17 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_usergroup_options_usergroup_admin_contact_and_more'),
        ('accounts', '0007_reviews_usergroup_reviews'),
    ]

    operations = [
    ]
