# Generated by Django 4.0.2 on 2022-03-17 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_merge_20220317_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='reviews',
        ),
        migrations.AddField(
            model_name='reviews',
            name='group',
            field=models.ForeignKey(default=str, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.usergroup'),
            preserve_default=False,
        ),
    ]
