# Generated by Django 4.0.2 on 2022-03-22 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_reviews_group_name_remove_usergroup_reviews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='date_published',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
