# Generated by Django 4.0.2 on 2022-02-15 12:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_groupupuser_interests_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='(rejected|pending|confirmed)$')])),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_receiver', to='accounts.usergroup')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_requestor', to='accounts.usergroup')),
            ],
            options={
                'db_table': 'matches',
            },
        ),
    ]
