# Generated by Django 4.0.2 on 2022-02-17 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_matching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='status',
            field=models.CharField(default='pending', max_length=10, validators=[django.core.validators.RegexValidator(message='Must be one of the following: rejected, pending or confirmed', regex='(rejected|pending|confirmed)$')]),
        ),
    ]
